apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: xiebiao360@outlook.com
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard-yameet-cn
  namespace: kubernetes-dashboard
spec:
  secretName: kubernetes-dashboard-certs
  secretTemplate:
    labels:
      k8s-app: kubernetes-dashboard
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  # subject:
  #   organizations:
  #     - jetstack
  dnsNames:
    - dashboard.yameet.cn
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
